FROM apache/airflow:2.9.3-python3.11

USER airflow

# Install Python packages Airflow tasks will need
RUN pip install --no-cache-dir \
    astronomer-cosmos \
    apache-airflow-providers-postgres \
    apache-airflow-providers-common-sql \
    pandas \
    psycopg2-binary \
    requests

# Install dbt-postgres into a dedicated venv
RUN python -m venv /opt/airflow/dbt_venv && \
    . /opt/airflow/dbt_venv/bin/activate && \
    pip install --no-cache-dir dbt-postgres && \
    deactivate
